#!/usr/bin/env bash
#instal nginx
sudo apt update
sudo apt-get install nginx -y
sudo ufw allow 22
sudo ufw allow 80
sudo ufw enable
sudo ufw status
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

sudo service nginx status
curl localhost
