#!/usr/bin/env bash
#installing nginx
sudo apt update
apt-get install nginx -y
sudo ufw allow 22
sudo ufw allow 80
sudo ufw enable
udo ufw status
systemctl status nginx

sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

service nginx restart
