#!/usr/bin/env bash
#Configure Nginx server 
sudo apt update
sudo apt install nginx -y
sudo ufw allow 22
sudo ufw allow 80
sudo ufw enable

echo "location /redirect_me {
    return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;
}" | sudo tee /etc/nginx/sites-available/redirect_me

sudo ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/
sudo rm /etc/nginx/sites-enabled/default
sudo service nginx restart
