#!/usr/bin/env bash
#Configuring Nginx server 
sudo apt update
sudo apt-get install nginx -y
sudo ufw allow 22
sudo ufw allow 80
sudo ufw enable
sudo sed -i '/server_name _;/a \\n    location \/redirect_me {' /etc/nginx/sites-available/default
sudo sed -i '/location \/redirect_me {/a \\n        return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;' /etc/nginx/sites-available/default
sudo sed -i '/return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;/a \\n    }' /etc/nginx/sites-available/default

sudo ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/
sudo rm /etc/nginx/sites-enabled/default
sudo service nginx restart
