#!/usr/bin/env bash
#page 404
sudo apt update
sudo apt install nginx -y
sudo ufw allow 22
sudo ufw allow 80
sudo ufw enable

echo "location /xyz {" | sudo tee -a /etc/nginx/sites-available/default
echo "    return 404 \"Ceci n'est pas une page\";" | sudo tee -a /etc/nginx/sites-available/default
echo "}" | sudo tee -a /etc/nginx/sites-available/default

sudo service nginx restart
