#!/usr/bin/env bash
#p404
sudo apt update
sudo apt install nginx -y
sudo ufw allow 22
sudo ufw allow 80
sudo ufw enable
sudo sed -i '/server_name _;/a \\n    location \/xyz {' /etc/nginx/sites-available/default
sudo sed -i '/location \/xyz {/a \\n        return 404 "Ceci n'est pas une page";' /etc/nginx/sites-available/default
sudo sed -i '/return 404 "Ceci n'\''est pas une page";/a \\n    }' /etc/nginx/sites-available/default
sudo service nginx restart
