#!/usr/bin/env bash

# Manages the script manage_my_process
MY_PROCESS_SCRIPT="./manage_my_process"
PID_FILE="/var/run/my_process.pid"

if [ "$1" == "start" ]; then
    if [ -e "$PID_FILE" ]; then
        echo "Process already started."
    else
        $MY_PROCESS_SCRIPT &
        touch $PID_FILE
        echo "$!" > $PID_FILE
        echo "manage_my_process started"
    fi
elif [ "$1" == "restart" ]; then
    if [ -e "$PID_FILE" ]; then
        echo "manage_my_process stopped"
        kill "$(cat $PID_FILE)"
        rm $PID_FILE
    fi
    $MY_PROCESS_SCRIPT &
    touch $PID_FILE
    echo "$!" > $PID_FILE
    echo "manage_my_process restarted"
elif [ "$1" == "stop" ]; then
    if [ -e "$PID_FILE" ]; then
        echo "manage_my_process stopped"
        kill "$(cat $PID_FILE)"
        rm $PID_FILE
    else
        echo "Process is not running."
    fi
else
    echo "Usage: $0 {start|stop|restart}"
    exit 1
fi

exit 0

