#!/usr/bin/env bash
# Manages the script manage_my_process
MY_PROCESS_SCRIPT="./my_process"
PID_FILE="/var/run/my_process.pid"
case "$1" in
    start)
        if [ -e "$PID_FILE" ]; then
            echo "Process already started."
        else
            $MY_PROCESS_SCRIPT &
            echo $! > $PID_FILE
            echo "my_process started"
        fi
        ;;
    stop)
        if [ -e "$PID_FILE" ]; then
            MY_PROCESS_PID=$(cat $PID_FILE)
            kill $MY_PROCESS_PID
            rm -f $PID_FILE
            echo "my_process stopped"
        else
            echo "Process is not running."
        fi
        ;;
    restart)
        if [ -e "$PID_FILE" ]; then
            MY_PROCESS_PID=$(cat $PID_FILE)
            kill $MY_PROCESS_PID
            rm -f $PID_FILE
            echo "my_process stopped"
        fi
        $MY_PROCESS_SCRIPT &
        echo $! > $PID_FILE
        echo "my_process restarted"
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
