#!/usr/bin/env bash

# The story of /etc/passwd file.
IFS=":"
while read -r username password userid groupname homedir shell; do
	echo "The user $username is part of the $groupid gang, lives in $homedir, and rides $shell."
	echo "$userid's place is protected by the passcode $password, more info about the user here: $username"
done < /etc/passwd
