#!/usr/bin/env bash
# Displays "Best School" 10 times - "Hi" on the 9th iteration
cnt=0
while [ $cnt -lt 10 ]; do
    if [ $cnt -eq 8 ]; then
        echo "Hi"
    else
        echo "Best School"
    fi
    ((cnt++))
done
