#!/usr/bin/env bash

# Displays numbers, and provides messages for specific iterations.
nbr=1
while [ $nbr -le 20 ]; do
	echo "$nbr"
	case $nbr in
		"4")
			echo "bad luck from China"
			;;
		"9")
			echo "bad luck from Japan"
			;;
		"17")
			echo "bad luck from Italy"
			;;
	esac
	((nbr++))
done
