#!/usr/bin/env bash

# Displays the time (12 hours and 59 minutes).
heure=0
while [ $heure -le 12 ]; do
    echo "Hour: $heure"
    minute=1
    while [$minute -le 59]; do 
	    echo "$minute"
	    (( minute++ ))
    done
    (( heure++ ))
done
