#!/usr/bin/env bash
# Displays information about `school`file with if and else.
SCHOOLFILE= "school"
if [ -e $SCHOOLFILE ]; then
	echo "$SCHOOLFILE file exists"
	if [ -f $SCHOOLFILE ]; then
		echo "$SCHOOLFILE is a regular file"
		if [ -s $SCHOOLFILE ]; then
			echo "$SCHOOLFILE file is not empty"
		else
			echo "$SCHOOLFILE file is empty"
		fi
	else
		echo "$SCHOOLFILE is not a regular file"
	fi
else
	echo "$SCHOOLFILE file does not exist"
fi
