#!/usr/bin/env bash
# Fixing my server to return 'Hello Holberton' for HTTP requests.
apt-get update
apt-get install -y apache2
service apache2 start
echo "Hello Holberton" > /var/www/html/index.html
curl http://localhost
update-rc.d apache2 defaults
