#!/usr/bin/env bash
# Configures Nginx to run as nginx user
sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen 80 /listen 8080 /' /etc/nginx/sites-available/default
service nginx restart
