#!/usr/bin/env bash
# Configures Nginx to listen on port 8080
sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf
sed -i '/listen 80 /c\ \ \ \ listen 8080;' /etc/nginx/sites-available/default
sed -i '/listen \[::\]:80 /c\ \ \ \ listen [::]:8080;' /etc/nginx/sites-available/default
service nginx restart
